Feature: Legal Cover for all ages

  Scenario Outline: Capture legal cover for all age bands.

    Given User log in SGUI OR shamba  website
    When  User Selects the desired plan option ,'<SelectPlan>'
    Then User then Selects the date of birth of the main life assured and the desired plan option '<PlanOPss>','<mainLifeDOB>'
    When   User Selects the plan option and then a consultant enters all the necessary required  details of the main member. '<Tittle>','<Name>','<Surname>','<SouthAfricanCitizen>','<IDNumber1>','<IDNumber2>','<DateOfBirth>','<MonthlyIncome>','<Occupation>','<Education>','<CellNumber>','<PostalAddress>','<PostalCode>',
    Then  A consultant enters required Spouse, child and  extended member details '<SpouseTitle>', '<SpouseName>','<spouseSurname>' , '<SpouseGender>', '<SpouseIDNumber>', '<ChildName>', '<childSurname>', '<childGen>', '<ChildIDNumber>', '<ChildIsStudent>','<ExtMemberTitle>','<ExtMmemberName>','<ExtMmemberSurname>','<ExtMmemberRelationship>','<PreFee>','<ExtMmemberGender>','<ExtMmemberIDNumber>','<ExtMemberTitleII>','<ExtMmemberNameII>','<ExtMmemberSurnameII>','<ExtMmemberRelationshipII>','<PreFeeII>','<ExtMmemberGenderII>','<ExtMmemberIDNumberII>','<ExtMemberTitleIII>','<ExtMmemberNameIII>','<ExtMmemberSurnameIII>','<ExtMmemberRelationshipIII>','<PreFeeIII>','<ExtMmemberGenderIII>','<ExtMmemberIDNumberIII>','<ExtMemberTitle4>','<ExtMmemberName4>','<ExtMmemberSurname4>','<ExtMmemberRelationship4>','<PreFee4>','<ExtMmemberGender4>','<ExtMmemberIDNumber4>'
    When  User adds beneficiary details as well as payer details and  proceeds with the cover and concludes the sale, '<BeneficiaryRelationship>', '<PayerTitle>','<PayerName>','<PayerSurname>','<PayerID1>','<PayerID2>','<Relationship>','<DebitDay>','<FirstDebitDay>','<BankName>', '<BranchCode>', '<AccountType>', '<AccountNumber1>','<AccountNumber2>','<MobileNumber>','<IsEmployee>', '<Convert>',



    Examples:
      |PlanOPss|  mainLifeDOB | Tittle| Name |Surname| SouthAfricanCitizen     | IDNumber1              |IDNumber2    |DateOfBirth| MonthlyIncome | Occupation | Education |CellNumber | PostalAddress |  PostalCode  |SelectPlan             |PayerTitle|PayerName|PayerSurname|PayerID1     |PayerID2     |Relationship|DebitDay|FirstDebitDay|BankName        |BranchCode|AccountType    |AccountNumber1|AccountNumber2|MobileNumber|IsEmployee|BeneficiaryRelationship|Convert                 |SpouseTitle|SpouseName|spouseSurname|SpouseGender|SpouseIDNumber|ChildName|childSurname|childGen|ChildIDNumber|ChildIsStudent|ExtMemberTitle|ExtMmemberName|ExtMmemberSurname|ExtMmemberRelationship|PreFee|ExtMmemberGender|ExtMmemberIDNumber|ExtMemberTitleII|ExtMmemberNameII|ExtMmemberSurnameII|ExtMmemberRelationshipII|PreFeeII|ExtMmemberGenderII|ExtMmemberIDNumberII|ExtMemberTitleIII|ExtMmemberNameIII|ExtMmemberSurnameIII|ExtMmemberRelationshipIII|PreFeeIII|ExtMmemberGenderIII|ExtMmemberIDNumberIII|ExtMemberTitle4|ExtMmemberName4|ExtMmemberSurname4|ExtMmemberRelationship4|PreFee4|ExtMmemberGender4|ExtMmemberIDNumber4|
      |Family  |  2001-06-03  | Miss  |Kamo  |Breeze |Yes                      | 9705086953994          |9705086953994|2022-06-03 | Up to 3,000   | Clerk      |Matric     |0625956363 |74 Hill Street | 2092         |Enhanced Extended Legal|Miss      |Tisetso  |Viks        |0004095879682|0004095879682|Cousin      |30      |30 Apr 2024  |CAPITEC BANK LTD|470010    |Savings Account|1234          |1234          |0601234230  |No        |Member Estate          |Enhanced Extended Legal |Mr         |Leeto     |Kgosi        |Male        |0004096178217 |Lame     |Kgomo       |Male    |2004096288972|No            |Mr            |Lerato        |Kgosi            |Brother               | Yes  |Male            |0004098313762     |Mr              |Kagiso          |Mmmitso            |Brother                 |Yes     |Male              |9705085791247       |Miss             |Tino             |Davids              |Cousin                   |Yes      |Female             |9905086397594        |Mr             |Mawande        |Veso              |Cousin                 |Yes    |Male             |9705088677195      |